### ISSUE TITLE
Make a Casdoor C++ SDK like other languages

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-cpp-sdk#1]
Refer to: https://casdoor.org/docs/how-to-connect/sdk

**Comment by hsluoyz** [comment]
@roguelxx

**Comment by hsluoyz** [comment]
@cs1137195420 can you work on this?

**Comment by cs1137195420** [comment]
> @cs1137195420 can you work on this?

Sure, I will work on it.
